use_default_settings: true

server:
  limiter: false

search:
  formats:
    - html
    - json

engines:
  - name: arxiv
    disabled: false
    timeout: 15
  - name: exa publications
    engine: exa
    shortcut: exap
    categories:
      - science
      - scientific publications
    disabled: false
    results_per_page: 16
    timeout: 15
  - name: exa web
    engine: exa
    shortcut: exaw
    categories:
      - general
      - web
    disabled: false
    search_category: ""
    results_per_page: 16
    timeout: 15
  - name: federal register
    engine: json_engine
    shortcut: fr
    categories:
      - government
      - news
    disabled: false
    paging: true
    search_url: "https://www.federalregister.gov/api/v1/documents.json?per_page=20&page={pageno}&conditions%5Bterm%5D={query}"
    results_query: results
    url_query: html_url
    title_query: title
    content_query: excerpts
    content_html_to_text: true
    timeout: 10
